export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const AUTHUPDATE = 'AUTHUPDATE';

export const CREATEBOOK = 'CREATEBOOK';
export const UPDATEBOOK = 'UPDATEBOOK';
export const DELETEBOOK = 'DELETEBOOK';
export const GETBOOK = 'GETBOOK';
export const GETALLBOOK = 'GETALLBOOK';

export const CREATEREQUEST = 'CREATEREQUEST';
export const UPDATEREQUEST = 'UPDATEREQUEST';
export const DELETEREQUEST = 'DELETEREQUEST';
export const GETREQUEST = 'GETREQUEST';

export const FETCH_ALLHEART = 'FETCH_ALLHEART';
export const HEARTPREDICTION = 'HEART_PREDICTION';
export const GET_TOTALPAGES = 'GET_TOTALPAGES';
